TelasRegionales/TelasRegionales/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TelasRegionales.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

TelasRegionales/TelasRegionales/Controllers/HomeTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace TelasRegionales.Controllers
{
    public class HomeTController : Controller
    {
        // GET: HomeT
        public ActionResult Index()
        {
            return View();
        }

    }
}

TelasRegionales/TelasRegionales/Controllers/MisionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TelasRegionales.Controllers
{
    public class MisionController : Controller
    {
        // GET: Mision
        public ActionResult Index()
        {
            return View();
        }
    }
}

TelasRegionales/TelasRegionales/Controllers/VisionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TelasRegionales.Controllers
{
    public class VisionController : Controller
    {
        // GET: Vision
        public ActionResult Index()
        {
            return View();
        }
    }
}

TelasRegionales/TelasRegionales/Views/Shared/LayoutT.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="es" xml:lang="es">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta name="google-site-verification" content="rIP9ZglzWE_bsajWUp74z4SKA_NdLPejcfiopzBeBJo" />
    <title>Telas Regionales</title>

    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <link rel="shortcut icon" href="img/fav.png">
    <!-- Author Meta -->
    <meta name="author" content="colorlib">
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Telas Regionales</title>

    <!--
    CSS
    ============================================= -->
    <link rel="alternate" hreflang="es">
    <link href="~/css/linearicons.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/css/nice-select.css" rel="stylesheet" />
    <link href="~/css/animate.min.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />

    <link href="~/css/jquery-ui.css" rel="stylesheet" />


    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")




</head>
<body>


    <header id="header">
        <div class="container main-menu">
            <div class="row align-items-center justify-content-between d-flex">
                <div id="logo" style="padding-right:290px">
                    <a href="@Url.Action("index","HomeT")"><img style="width:250px; " src="~/img/head.png" alt="logohead" /></a>
                </div>
                <nav id="nav-menu-container">
                    <ul class="nav-menu">
                        <li><a href="@Url.Action("index","HomeT")"> Inicio</a></li>
                        <li><a href="@Url.Action("index","About")">Nosotros</a></li>
                        <li><a href="@Url.Action("index","Mision")">Misión</a></li>
                        <li><a href="@Url.Action("index","Vision")">Visión</a></li>
                        <li><a href="@Url.Action("index","Portfolio")">Portafolio</a></li>

                        <li><a href="@Url.Action("index","Contact")">Contacto</a></li>
                    </ul>
                </nav><!-- #nav-menu-container -->
            </div>
        </div>
    </header><!-- #header -->
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    <!-- start footer Area -->
    <footer class="footer-area section-gap">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-sm-6">
                    <div class="single-footer-widget">
                        <h4>Conócenos</h4>
                        <p>
                            <ul>
                                <li><a href="@Url.Action("index","About")">Nosotros</a></li>
                                <li><a href="@Url.Action("index","Mision")">Misión</a></li>
                                <li><a href="@Url.Action("index","Vision")">Visión</a></li>
                            </ul>
                        </p>
                        <p class="footer-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            Copyright &copy; Derechos reservados. 2018
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6 col-sm-6">

                </div>
                <div class="col-lg-2 col-md-6 col-sm-6 social-widget">
                    <div class="single-footer-widget">
                        <h4>Síguenos</h4>
                        <p>Redes Sociales</p>
                        <div class="footer-social d-flex align-items-center">
                            <a href="https://www.facebook.com/telas.merida.77"><i class="fa fa-facebook"></i></a>
                            <a href="https://twitter.com/MeridaTelas"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End footer Area -->
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-121187885-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'UA-121187885-1');
    </script>


    <script src="~/js/vendor/jquery-2.2.4.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/vendor/bootstrap.min.js"></script>

    <script src="~/js/easing.min.js"></script>
    <script src="~/js/hoverIntent.js"></script>
    <script src="~/js/superfish.min.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
    @*<script src="~/js/jquery.magnific-popup.min.js"></script>*@
    <script src="~/js/jquery.tabs.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/isotope.pkgd.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/simple-skillbar.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    @*<script src="~/js/main.js"></script>*@
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TelasRegionales/TelasRegionales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                   
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>